version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=mysql+pymysql://root:example@db:3306/dev?charset=utf8mb4
    depends_on:
      - db
    networks:
      - testing-network
      - service-network
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - .dbdata:/var/lib/mysql
      - ./initDb.sql:/data/application/init.sql
    ports: 
      - 3306:3306
    command: --init-file /data/application/init.sql
    networks:
      - service-network
 
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8082:80
    networks:
      - testing-network
      - service-network
    depends_on:
      - db

networks:
  service-network:
  testing-network:
    name: testing-network-global